### ISSUE TITLE
Handle schema branches for all sources rather than just Kafka

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1240]
1. Created a SAM app and added HDFS source
2. Entered schema name and selected version "1" and saved (the output fields are populated)
3. Edit the source again.

The schema version is missing in the component dialog. See screenshot.

<img width="472" alt="screen shot 2018-03-14 at 11 05 01 am" src="https://user-images.githubusercontent.com/6792890/37422097-e4d35a46-2777-11e8-949a-cb70e3ba0870.png">

Cluster: http://ctr-e138-1518143905142-85179-01-000002.hwx.site:8080/api/v1/clusters/cl1
Schema registry url: http://hdf-3-1-release3.field.hortonworks.com:7788/

**Comment by arunmahadevan** [comment]
Now when I try the schema never shows up. In the backend i see a request with schema name "undefined".

**Comment by priyank5485** [comment]
https://github.com/hortonworks/streamline/pull/1243

**Comment by priyank5485** [comment]
@shahsank3t @joylyn 

While handling ui changes in https://github.com/hortonworks/streamline/pull/1204/files  for backend changes in https://github.com/hortonworks/streamline/pull/1200 it seems that we missed a few things.

Can we fix the below?

1. It seems that default value of MASTER for schema branch is hardcoded for field name. Quoting an example for source at https://github.com/hortonworks/streamline/pull/1204/files#diff-700814ca73bcf79d2404b6826901cebfR115 Ditto for sink. Can we change the logic in that if clause such that we use hint instead of fieldName? So, if there are any fields for that source/sink that have a hint of schemaBranch and if they dont have a value then we assign the default value of master. 
2. The logic for getting all branches for a schema also seems to be hard coded just for Kafka. https://github.com/hortonworks/streamline/pull/1204/files#diff-700814ca73bcf79d2404b6826901cebfR145 ditto for sink. That is making all other sources fail. I dont see a call being made to fetch branches for other sources like hdfs, eventhub, etc after applying json file changes in this PR. Can we change that logic instead to use the hints schemaBranch and dependsOn-<field with hint schema> to make it generic and work for all ?

In general if you guys come across any UI api calls that are hardcoded using field names, please change it to use hints as well, unless its a special case.

@arunmahadevan The changes I have pushed in this PR are necessary and will not break anything. However they are not sufficient and we need UI fixes as mentioned above as well to fix this issue.

**Comment by arunmahadevan** [comment]
Thanks @priyank5485 , @sameer79 for the patch, merged to master.
