### ISSUE TITLE
Turn off test mode for now

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#668]
Application test mode needs a little bit of work to get to a polished state. I think for now we should turn off test mode in the UI and enable it in a subsequent release.

@harshach @shahsank3t

**Comment by harshach** [comment]
@sureshms I lean towards to shipping it. Can we make this decision next week depending on priorities if we can't get it we will hide it. Also can you list out the issues that you see right now

**Comment by sureshms** [comment]
@harshach I am not sure about the current UX. It just adds more complexity. That said, I am going to test it and come up with concrete set of issues. If we decide to include it, I am fine. For now let's make this issue p1.

**Comment by HeartSaVioR** [comment]
Current UX doesn't cover adding sink expected output, and also doesn't provide showing test histories btw. It only has event log related feature now. This seems a bit out of sync with what we've designed.

**Comment by arunmahadevan** [comment]
A few issues with test mode -
https://hortonworks.jira.com/browse/BUG-81212
https://hortonworks.jira.com/browse/BUG-81216
https://hortonworks.jira.com/browse/BUG-81218

If we plan to ship test mode we should consider addressing the above. The test mode currently does not produce any output for time based window/aggregate since it runs for a fixed duration (30 secs). So may be we should expose additional options for users control when to emit data from sources and how long to run the tests (may be by clicking start/stop/emit buttons)

**Comment by arunmahadevan** [comment]
We can also have an option for users to enter inputs while the tests are running and continuously show the generated outputs until the user stops the tests. (something like kafka console producer/consumer). Right now the tests are more like a batch job.

**Comment by shahsank3t** [comment]
For now, we have hidden test mode from UI.
Commit id: https://github.com/hortonworks/streamline/commit/9d7fb0b9e79eaee014c3e3f3ef4bc9aa150b8044
