### ISSUE TITLE
UI issues: P2

### ISSUE THREAD

**Issue by ggolani** [hortonworks/streamline#680]
- when switching to schema-registry from Streamline, allow navigation option to go back to Streamline (workaround: browser back button)

- when user "analyst" logs on, do not show the following page, only show the dashboards page, which should have  a user-friendly option if empty.
<img width="1258" alt="screen shot 2017-05-26 at 3 18 35 pm" src="https://cloud.githubusercontent.com/assets/5951352/26514416/925ee816-4226-11e7-9ae5-b84a64605f40.png">

**Comment by shahsank3t** [comment]
@ggolani @harshach 

> when user "analyst" logs on, do not show the following page, only show the dashboards page, which should have a user-friendly option if empty.

Since the dashboard is just a redirection from streamline to superset's UI, it doesn't really look good to land a user over there. So instead of showing the current page(the one attached) we are now showing "No Data Found" if no application is accessible by that user.

Fixed in commit: https://github.com/hortonworks/streamline/commit/d06391802bf5c3ccbb8185cc975422b18db18015
