### ISSUE TITLE
Join processor output when both streams have same field

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#968]
When there are common fields in streams being joined, the output field selection lists the field only once. Its not clear from which stream the value is selected and send to the output.

Please discuss with @roshannaik on the behavior and how similar fields in different streams may be selected.

**Comment by shahsank3t** [comment]
@arunmahadevan 
After discussing this with @roshannaik we decided to let user select duplicate fields and ask them to enter the alias name that will be referred into the output fields.
To provide consistency, we will also let the user edit other fields alias but by default, it will be pre-fill with the field name.

Since it's UI related changes, @sameer79 assigning this to you.

**Comment by sameer79** [comment]
Raised PR : https://github.com/hortonworks/streamline/pull/991
