### ISSUE TITLE
Realtime join processor UI bugs

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#973]
**Bugs:**
1. In Output Fields Selection, if you select a field with the same name from both streams, it only accepts one... easily seen by doing SelectAll option. The backend allows disambiguation of names using the "streamname:fieldname" syntax.
2. Pressing OK button does not save and dismiss the dialog box (Do not select "unique" checkbox to reproduce this)
3. Do we have support or nested fields on UI? Backend allows nested fields using dot syntax. For eg: "streamname:fieldname" or ""streamname:nested.field.name"

**Minor changes:**
1. Please change all 4 occurrences of the word "Buffer" to "Window".
2. Rename "Conditional Fields" to "Join Criteria"

**Comment by shahsank3t** [comment]
@satishwaghela can you look it, please?

**Comment by shahsank3t** [comment]
@satishwaghela 
Adding another point in bugs:
4. Should default to fields grouping and the fields should be based on the fields used in the join condition used.

**Comment by roshannaik** [comment]
@shahsank3t  there is a UI bug wrt to how the output schema is shown when selecting nested fields.  this applies to both Join and newer RTJoin. 
When selecting a leaf node, it should not display all the upper nesting levels. The leaf node should just appear as top level node in the output schema.

**More generally**, since we are allowing selection of at any level of a nested hierarchy, you should display everything from the selected level and any child levels inside it.

Assuming the input has a nested field like this:   orginfo { busines_unit { department }, location }
- If you select  orginfo ... then orginfo and everything under it should show up preserving the hierarch.
- if you select business_info, then businessinfo and everything under it will show up as a top level entity. It wont get nested under orginfo.
- if you select both leaf nodes location & department then both of them should shows up as a independent top level entities. they should not be put under their parent levels.

Currently selecting department, will show this hierarchy  orginfo -> busines_unit -> department  in the output schema.

Ping me if you need further clarification.

**Comment by roshannaik** [comment]
Here are some of the UI changes i can think of that we need to fix:
- The new alias-ing ability (from Join Processor), and reflecting the alias in downstream component's input schema.
- Handling of nested fields .. in output fields selection. (same as Join Processor)
- Applying fields grouping to the input streams based on the join keys specified in UI.
- Rename the component to 'Rolling Window Join'
- Please change all 4 occurrences of the word "Buffer" to "Window".
- Rename "Conditional Fields" to "Join Criteria"

*Note*: We are not enabling event-time support for this right now.

**Comment by satishwaghela** [comment]
Raised PR: https://github.com/hortonworks/streamline/pull/1068
